import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "400",
});

export const metadata: Metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR" className={poppins.variable} data-theme="dark">
      <body className="min-h-screen flex flex-col">
        <Header></Header>
        <main className="flex-grow flex items-center justify-center">
          {children}
        </main>

        <Footer></Footer>
      </body>
    </html>
  );
}
